---
- name: Check for ovftool
  shell: pkgutil --pkgs | awk '/com.vmware.ovftool.application/'
  register: wlc_pkgutil_ovftool
  changed_when: False
- name: Fail if VMWare OVF Tools are not installed
  fail: msg="VMWare OVF Tools are required.  Please install and retry."
  when: 'not {{ wlc_pkgutil_ovftool.stdout | match("com.vmware.ovftool.application") }}'
- name: Get ovftool path
  shell: pkgutil --files com.vmware.ovftool.application | grep -FE 'ovftool$'
  register: wlc_ovftool_path
  changed_when: false
- name: Check VM path
  stat: path='{{ wlc_vm_safe_dst_full_path }}'
  register: wlc_vm_exists
  changed_when: False
- name: Fail if VM path exists
  fail: msg="VM already exists.  Please set wlc_vm_overwrite variable to any value to overwrite the existing VM"
  when: (wlc_vm_exists.stat.isdir is defined) and (wlc_vm_overwrite is not defined)