---
- name: Remove previous DHCP reservations
  blockinfile:
    dest: '{{ wlc_dhcpd_conf_path }}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ wlc_vm_name }} {{ wlc_vm_ip_address }}"
    content: ""
  become: yes
- name: Add DHCP reservation
  blockinfile:
    dest: '{{ wlc_dhcpd_conf_path }}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ wlc_vm_name }} {{ wlc_vm_ip_address }}"
    insertafter: EOF
    content: |
      host {{ wlc_vm_name }} {
        hardware ethernet {{ wlc_vm_mac_address }};
        fixed-address {{ wlc_vm_ip_address }};
        option domain-name-servers {{ wlc_vm_ip_gateway }};
        option domain-name localdomain;
        default-lease-time 1200;
        max-lease-time 1200;  
        option routers {{ wlc_vm_ip_gateway }};
        next-server {{ wlc_host_ip_address }};
      }
  become: yes
  notify:
    - stop vmware networking
    - start vmware networking
    - start vm headless
- meta: flush_handlers