---
- name: Add entry to hosts file
  lineinfile: 
    dest: /etc/hosts
    line: '{{ wlc_vm_ip_address }} {{ wlc_vm_name }}'
    regexp: '{{ wlc_vm_name }}$'
    insertafter: EOF
  when: wlc_vm_persist_dhcp_reservation
  become: yes